import { Client, Batch, Card, ActivityLog } from '../types';

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli_01',
    business_name: 'ABC Salon & Spa',
    contact_name: 'Sarah Jenkins',
    phone: '+1 (555) 234-5678',
    email: 'sarah@abcsalon.com',
    notes: 'Premium PVC cards with matte finish. Google review boost campaign.',
    status: 'Active',
    created_at: '2026-02-10T09:30:00.000Z',
    card_count: 50,
  },
  {
    id: 'cli_02',
    business_name: 'Apex Dental Care',
    contact_name: 'Dr. Michael Chen',
    phone: '+1 (555) 876-5432',
    email: 'mchen@apexdental.com',
    notes: 'Countertop NFC stands and reception review cards.',
    status: 'Active',
    created_at: '2026-02-14T11:15:00.000Z',
    card_count: 25,
  },
  {
    id: 'cli_03',
    business_name: 'Grandview Bistro & Bar',
    contact_name: 'Marco Rossi',
    phone: '+1 (555) 432-1098',
    email: 'marco@grandviewbistro.com',
    notes: 'Table tent NFC cards for diners leaving reviews after payment.',
    status: 'Active',
    created_at: '2026-02-20T14:45:00.000Z',
    card_count: 40,
  },
  {
    id: 'cli_04',
    business_name: 'Urban Fitness Studio',
    contact_name: 'Elena Rostova',
    phone: '+1 (555) 765-4321',
    email: 'elena@urbanfit.io',
    notes: 'Membership exit review prompt cards.',
    status: 'Active',
    created_at: '2026-02-28T08:00:00.000Z',
    card_count: 30,
  },
  {
    id: 'cli_05',
    business_name: 'Elite Auto Repair & Detail',
    contact_name: 'Dave Henderson',
    phone: '+1 (555) 987-6543',
    email: 'dave@eliteautocare.com',
    notes: 'Keychain NFC tags + invoice review card.',
    status: 'Inactive',
    created_at: '2026-03-05T16:20:00.000Z',
    card_count: 15,
  },
  {
    id: 'cli_06',
    business_name: 'Zenith Boutique Hotel',
    contact_name: 'Claire Beauchamp',
    phone: '+1 (555) 345-6789',
    email: 'concierge@zenithhotel.com',
    notes: 'Room keycard holder with NFC review prompt.',
    status: 'Active',
    created_at: '2026-03-12T10:00:00.000Z',
    card_count: 60,
  },
];

export const INITIAL_BATCHES: Batch[] = [
  {
    id: 'batch_01',
    client_id: 'cli_01',
    client_name: 'ABC Salon & Spa',
    batch_name: 'ABC-Salon-Batch-1',
    quantity: 50,
    status: 'Completed',
    destination_url: 'https://g.page/r/abc-salon-review/review',
    created_at: '2026-02-10T10:00:00.000Z',
  },
  {
    id: 'batch_02',
    client_id: 'cli_02',
    client_name: 'Apex Dental Care',
    batch_name: 'Apex-Dental-Batch-1',
    quantity: 25,
    status: 'Completed',
    destination_url: 'https://g.page/r/apex-dental-review/review',
    created_at: '2026-02-14T12:00:00.000Z',
  },
  {
    id: 'batch_03',
    client_id: 'cli_03',
    client_name: 'Grandview Bistro & Bar',
    batch_name: 'Grandview-Bistro-Tables',
    quantity: 40,
    status: 'Processing',
    destination_url: 'https://g.page/r/grandview-bistro-food/review',
    created_at: '2026-02-20T15:30:00.000Z',
  },
  {
    id: 'batch_04',
    client_id: 'cli_04',
    client_name: 'Urban Fitness Studio',
    batch_name: 'Urban-Fit-Promo-1',
    quantity: 30,
    status: 'Draft',
    destination_url: 'https://g.page/r/urban-fitness-reviews/review',
    created_at: '2026-03-01T11:00:00.000Z',
  },
];

export const INITIAL_CARDS: Card[] = [
  {
    id: 'card_001',
    internal_card_no: 'CARD-0001',
    public_token: '7KQ4M8X2',
    client_id: 'cli_01',
    client_name: 'ABC Salon & Spa',
    batch_id: 'batch_01',
    batch_name: 'ABC-Salon-Batch-1',
    original_url: 'https://g.page/r/abc-salon-review/review',
    destination_url: 'https://g.page/r/abc-salon-review/review',
    status: 'Delivered',
    total_scans: 142,
    created_at: '2026-02-10T10:05:00.000Z',
    updated_at: '2026-03-10T14:20:00.000Z',
  },
  {
    id: 'card_002',
    internal_card_no: 'CARD-0002',
    public_token: '9XP2K1R8',
    client_id: 'cli_01',
    client_name: 'ABC Salon & Spa',
    batch_id: 'batch_01',
    batch_name: 'ABC-Salon-Batch-1',
    original_url: 'https://g.page/r/abc-salon-review/review',
    destination_url: 'https://g.page/r/abc-salon-review/review',
    status: 'Sold',
    total_scans: 98,
    created_at: '2026-02-10T10:05:00.000Z',
    updated_at: '2026-03-08T11:15:00.000Z',
  },
  {
    id: 'card_003',
    internal_card_no: 'CARD-0003',
    public_token: '4MN8T5W3',
    client_id: 'cli_01',
    client_name: 'ABC Salon & Spa',
    batch_id: 'batch_01',
    batch_name: 'ABC-Salon-Batch-1',
    original_url: 'https://g.page/r/abc-salon-review/review',
    destination_url: 'https://g.page/r/abc-salon-special-promo',
    status: 'Ready',
    total_scans: 64,
    created_at: '2026-02-10T10:05:00.000Z',
    updated_at: '2026-03-15T09:40:00.000Z',
  },
  {
    id: 'card_004',
    internal_card_no: 'CARD-0004',
    public_token: '3HZ7P9L2',
    client_id: 'cli_02',
    client_name: 'Apex Dental Care',
    batch_id: 'batch_02',
    batch_name: 'Apex-Dental-Batch-1',
    original_url: 'https://g.page/r/apex-dental-review/review',
    destination_url: 'https://g.page/r/apex-dental-review/review',
    status: 'Printed',
    total_scans: 35,
    created_at: '2026-02-14T12:10:00.000Z',
    updated_at: '2026-02-25T16:00:00.000Z',
  },
  {
    id: 'card_005',
    internal_card_no: 'CARD-0005',
    public_token: '8VR6Y3K9',
    client_id: 'cli_02',
    client_name: 'Apex Dental Care',
    batch_id: 'batch_02',
    batch_name: 'Apex-Dental-Batch-1',
    original_url: 'https://g.page/r/apex-dental-review/review',
    destination_url: 'https://g.page/r/apex-dental-review/review',
    status: 'Link Pending',
    total_scans: 0,
    created_at: '2026-02-14T12:10:00.000Z',
    updated_at: '2026-02-14T12:10:00.000Z',
  },
  {
    id: 'card_006',
    internal_card_no: 'CARD-0006',
    public_token: '5LT4C2E7',
    client_id: 'cli_03',
    client_name: 'Grandview Bistro & Bar',
    batch_id: 'batch_03',
    batch_name: 'Grandview-Bistro-Tables',
    original_url: 'https://g.page/r/grandview-bistro-food/review',
    destination_url: 'https://g.page/r/grandview-bistro-food/review',
    status: 'Ready',
    total_scans: 112,
    created_at: '2026-02-20T15:35:00.000Z',
    updated_at: '2026-03-12T17:30:00.000Z',
  },
  {
    id: 'card_007',
    internal_card_no: 'CARD-0007',
    public_token: '2BQ9W8M4',
    client_id: 'cli_03',
    client_name: 'Grandview Bistro & Bar',
    batch_id: 'batch_03',
    batch_name: 'Grandview-Bistro-Tables',
    original_url: 'https://g.page/r/grandview-bistro-food/review',
    destination_url: 'https://g.page/r/grandview-bistro-food/review',
    status: 'Draft',
    total_scans: 0,
    created_at: '2026-02-20T15:35:00.000Z',
    updated_at: '2026-02-20T15:35:00.000Z',
  },
  {
    id: 'card_008',
    internal_card_no: 'CARD-0008',
    public_token: '6DF1N9V5',
    client_id: 'cli_05',
    client_name: 'Elite Auto Repair & Detail',
    batch_id: 'batch_01',
    batch_name: 'Elite-Auto-Cards',
    original_url: 'https://g.page/r/elite-auto-care/review',
    destination_url: 'https://g.page/r/elite-auto-care/review',
    status: 'Disabled',
    total_scans: 19,
    created_at: '2026-03-05T16:30:00.000Z',
    updated_at: '2026-03-18T10:00:00.000Z',
  },
];

export const INITIAL_ACTIVITY: ActivityLog[] = [
  {
    id: 'act_01',
    action: 'Card Scanned',
    description: 'Card CARD-0001 (ABC Salon) received a verified scan',
    timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    type: 'card',
    entity_id: 'card_001',
  },
  {
    id: 'act_02',
    action: 'Destination Updated',
    description: 'Updated destination URL for CARD-0003 to special promo campaign',
    timestamp: new Date(Date.now() - 1000 * 60 * 85).toISOString(),
    type: 'destination',
    entity_id: 'card_003',
  },
  {
    id: 'act_03',
    action: 'Card Marked Delivered',
    description: 'Card CARD-0001 marked as Delivered to ABC Salon & Spa',
    timestamp: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    type: 'status',
    entity_id: 'card_001',
  },
  {
    id: 'act_04',
    action: 'Batch Created',
    description: 'Batch Grandview-Bistro-Tables (40 cards) generated for Grandview Bistro & Bar',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    type: 'batch',
    entity_id: 'batch_03',
  },
  {
    id: 'act_05',
    action: 'New Client Created',
    description: 'Zenith Boutique Hotel registered in system with 60 target cards',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
    type: 'client',
    entity_id: 'cli_06',
  },
  {
    id: 'act_06',
    action: 'Card Generated',
    description: 'Card CARD-0004 generated with token 3HZ7P9L2',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    type: 'card',
    entity_id: 'card_004',
  },
];
